MalhariaWeb/Models/MAQUINAS.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;

namespace MalhariaWeb.Models
{
    public class MAQUINAS
    {
        [Key]
        [DisplayName("Id")]
        public int ID_MAQUINA { get; set; }
        [DisplayName("Maquina")]
        public string NOME_MAQUINA { get; set; }
    }
}

MalhariaWeb/Controllers/MaquinasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MalhariaWeb.Models;
using MalhariaWeb.Roles;

namespace MalhariaWeb.Controllers
{
    public class MaquinasController : Controller
    {
        private ContextDB db = new ContextDB();

        //
        // GET: /Maquinas/
        [Filtro(Roles = "PCP")]
        public ActionResult Index()
        {
            return View(db.MAQUINAS.ToList());
        }

        //
        // GET: /Maquinas/Details/5

        [Filtro(Roles = "PCP")]
        public ActionResult Details(int id = 0)
        {
            MAQUINAS maquinas = db.MAQUINAS.Find(id);
            if (maquinas == null)
            {
                return HttpNotFound();
            }
            return View(maquinas);
        }

        //
        // GET: /Maquinas/Create

        [Filtro(Roles = "PCP")]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Maquinas/Create

        [HttpPost]
        [Filtro(Roles = "PCP")]
        public ActionResult Create(MAQUINAS maquinas)
        {
            if (ModelState.IsValid)
            {
                db.MAQUINAS.Add(maquinas);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(maquinas);
        }

        //
        // GET: /Maquinas/Edit/5

        [Filtro(Roles = "PCP")]
        public ActionResult Edit(int id = 0)
        {
            MAQUINAS maquinas = db.MAQUINAS.Find(id);
            if (maquinas == null)
            {
                return HttpNotFound();
            }
            return View(maquinas);
        }

        //
        // POST: /Maquinas/Edit/5

        [HttpPost]
        [Filtro(Roles = "PCP")]
        public ActionResult Edit(MAQUINAS maquinas)
        {
            if (ModelState.IsValid)
            {
                db.Entry(maquinas).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(maquinas);
        }

        //
        // GET: /Maquinas/Delete/5

        [Filtro(Roles = "PCP")]
        public ActionResult Delete(int id = 0)
        {
            MAQUINAS maquinas = db.MAQUINAS.Find(id);
            if (maquinas == null)
            {
                return HttpNotFound();
            }
            return View(maquinas);
        }

        //
        // POST: /Maquinas/Delete/5

        [HttpPost, ActionName("Delete")]
        [Filtro(Roles = "PCP")]
        public ActionResult DeleteConfirmed(int id)
        {
            MAQUINAS maquinas = db.MAQUINAS.Find(id);
            db.MAQUINAS.Remove(maquinas);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MalhariaWeb/Views/Maquinas/Create.cshtml
@model MalhariaWeb.Models.MAQUINAS

@{
    Layout = "~/Views/_LayoutMalhariaWeb.cshtml";
    ViewBag.Title = "Create";
}

<div class="row">
    <div class="col-md-12">

        <ul class="breadcrumb">
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li class="active">Cadastro</li>
            <li>Maquinas</li>
        </ul>

        @using (Html.BeginForm("Create", "Maquinas", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            @Html.ValidationSummary(true)

            <fieldset>

                <div class="form-group">
                    @Html.LabelFor(model => model.NOME_MAQUINA, new { @class = "col-md-2 control-label" })
                    @Html.TextBoxFor(model => model.NOME_MAQUINA, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.NOME_MAQUINA)
                </div>

                <p>
                    <button class="btn btn-success" type="submit" value="Salvar">Create</button>
                </p>
            </fieldset>
        }

    </div>
</div>

MalhariaWeb/Views/Maquinas/Delete.cshtml
@model MalhariaWeb.Models.MAQUINAS

@{
    Layout = null;
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>MAQUINAS</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ID_MAQUINA)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ID_MAQUINA)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.NOME_MAQUINA)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NOME_MAQUINA)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

MalhariaWeb/Views/Maquinas/Details.cshtml
@model MalhariaWeb.Models.MAQUINAS

@{
    Layout = null;
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>MAQUINAS</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ID_MAQUINA)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ID_MAQUINA)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.NOME_MAQUINA)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NOME_MAQUINA)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new {  id=Model.ID_MAQUINA }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MalhariaWeb/Views/Maquinas/Edit.cshtml
@model MalhariaWeb.Models.MAQUINAS

@{
    Layout = "~/Views/_LayoutMalhariaWeb.cshtml";
    ViewBag.Title = "Edit";
}

<div class="row">
    <div class="col-md-4">

        <ul class="breadcrumb">
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li class="active">Cadastro</li>
            <li>Maquinas</li>
        </ul>

        <div class="panel panel-primary">
            <div class="panel-heading">Máquinas</div>
            <div class="panel-body">

                @using (Html.BeginForm("Edit", "Maquinas", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horinzontal", role = "role" }))
                @using (Html.BeginForm())
                {
                    @Html.ValidationSummary(true)

                    <fieldset>
                        @Html.HiddenFor(model => model.ID_MAQUINA)
                        <div class="form-group">
                            @Html.LabelFor(model => model.NOME_MAQUINA, new { @class = "col-md-2 control-label" })
                            @Html.TextBoxFor(model => model.NOME_MAQUINA, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.NOME_MAQUINA)
                        </div>
                        <br>
                        <p>
                            <input type="submit" class="btn btn-success" value="Salvar" />
                        </p>
                    </fieldset>
                }

            </div>
        </div>

    </div>
</div>

MalhariaWeb/Views/Maquinas/Index.cshtml
@model IEnumerable<MalhariaWeb.Models.MAQUINAS>

@{
    Layout = "~/Views/_LayoutMalhariaWeb.cshtml";
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-md-4">

        <ul class="breadcrumb">
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li class="active">Cadastro</li>
            <li>Maquina</li>
        </ul>


        <div class="panel panel-primary">
            <div class="panel-heading">Máquinas</div>
            <div class="panel-body">


                <p>
                    <input type="button" class="btn btn-success" title="Delete" value="Novo" onclick="location.href='@Url.Action("Create")    '" />
                    <a id="modal-excluir" href="#modal-container-excluir" role="button" class="btn btn-danger" data-toggle="modal">Excluir</a>
                </p>


                <div id="gridContent">
                    @{WebGrid grid = new WebGrid(Model, rowsPerPage : 4);}
                    @grid.GetHtml(
                              htmlAttributes: new { @class = "table table-bordered", @id = "Grid1" },
                              columns: grid.Columns(
                                                     grid.Column(String.Empty, format: @<text>@Html.CheckBox("deleteInputs", new { Value = @item.ID_MAQUINA })</text>),
                                                     grid.Column("NOME_MAQUINA", "Máquina"),
                                                     grid.Column(header: "Ação", format: @<text><a href="@Url.Action("Edit", new { id = item.ID_MAQUINA })" title="Edit">
                                                         <img src="~/img/edit.png" /></a></text>)))
                </div>

            </div>
        </div>

        <div id="modal-container-excluir" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h3 id="myModalLabel">Exclusão</h3>
                    </div>
                    <div class="modal-body">
                        <div class="col-md-2" style="float: left">
                            <img alt="48x48" src="~/img/excluir_sels.png" />
                        </div>
                        <div>
                            <p>
                                <h4>Deseja excluir todos os itens selecionados?</h4>
                            </p>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-danger" id="confirmFalse" data-dismiss="modal" aria-hidden="true">Não</button>
                        <button class="btn btn-success" type="submit" id="confirmTrue">Sim</button>
                    </div>
                </div>
                <div>
                </div>


            </div>
        </div>