MalhariaWeb/Models/ORDEM_ACABAMENTO.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MalhariaWeb.Models
{
    public class ORDEM_ACABAMENTO
    {
        [Key]
        [DisplayName("#Ordem")]
        public int ID_ORDEM_ACABAMENTO { get; set; }
        [DisplayName("Produto")]
        public int ID_PRODUTO { get; set; }
        [DisplayName("Observação")]
        public string OBSERVACAO { get; set; }
        [DisplayName("Cor")]
        public int ID_COR { get; set; }
        [DisplayName("Metros Originais")]
     //   [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public double METROS_ORIGINAIS { get; set; }
        [DisplayName("Kilos Originais")]
  //      [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public double KILOS_ORIGINAIS { get; set; }
        [DisplayName("Metros Acabados")]
  //      [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public double METROS_ACABADOS { get; set; }
        [DisplayName("Kilos Acabados")]
 //       [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public double KILOS_ACABADOS { get; set; }
        [DisplayName("Situação")]
        public eTipoSituacao SITUACAO { get; set; }
        [DisplayName("Metros Programados")]
 //       [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public double METROS_PROGRAMADOS { get; set; }
        [DisplayName("Kilos Programados")]
 //       [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public double KILOS_PROGRAMADOS { get; set; }

        public List<ORDEM_ACABAMENTO_PECAS> ORDEM_ACABAMENTO_PECAS { get; set; }

        public virtual PRODUTO PRODUTO { get; set; }
        public virtual COR COR { get; set; }


    }

    public enum eTipoSituacao
    {
        Programado = 0,
        Cancelado = 1,
        Emitido = 2,
        Recebido = 3,
        Encerrado = 4
    }

}

MalhariaWeb/Controllers/OrdemAcabamentoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MalhariaWeb.Models;
using MalhariaWeb.Roles;

namespace MalhariaWeb.Controllers
{
    public class OrdemAcabamentoController : Controller
    {
        private ContextDB db = new ContextDB();

        [Filtro(Roles = "PCP")]
        public ActionResult Programado()
        {
            var ordem_acabamento = db.ORDEM_ACABAMENTO.Where(b => b.SITUACAO == eTipoSituacao.Programado).Include(b => b.PRODUTO).Include(b => b.COR);
            return View(ordem_acabamento.ToList());
        }

        [Filtro(Roles = "PCP")]
        public ActionResult Producao()
        {
            var ordem_acabamento = db.ORDEM_ACABAMENTO.Where(b => b.SITUACAO == eTipoSituacao.Emitido).Include(b => b.PRODUTO).Include(b => b.COR);
            return View(ordem_acabamento.ToList());
        }

        [Filtro(Roles = "PCP")]
        public ActionResult Retornado()
        {
            var ordem_acabamento = db.ORDEM_ACABAMENTO.Where(b => b.SITUACAO == eTipoSituacao.Recebido).Include(b => b.PRODUTO).Include(b => b.COR);
            return View(ordem_acabamento.ToList());
        }

        [Filtro(Roles = "PCP")]
        public ActionResult Emissao(int id = 0)
        {
            ORDEM_ACABAMENTO ordem_acabamento = db.ORDEM_ACABAMENTO.Find(id);
            List<ORDEM_ACABAMENTO_PECAS> ordem_acabamento_pecas = db.ORDEM_ACABAMENTO_PECAS.Where(p => p.ID_ORDEM_ACABAMENTO == id).ToList();
            ordem_acabamento.ORDEM_ACABAMENTO_PECAS = ordem_acabamento_pecas;
            if (ordem_acabamento == null)
            {
                return HttpNotFound();
            }
            return View(ordem_acabamento);
        }

        [Filtro(Roles = "PCP")]
        public ActionResult Revisao(int id = 0)
        {
            ORDEM_ACABAMENTO ordem_acabamento = db.ORDEM_ACABAMENTO.Find(id);
            List<ORDEM_ACABAMENTO_PECAS> ordem_acabamento_pecas = db.ORDEM_ACABAMENTO_PECAS.Where(p => p.ID_ORDEM_ACABAMENTO == id).ToList();
            ordem_acabamento.ORDEM_ACABAMENTO_PECAS = ordem_acabamento_pecas;
            var acondicionamento = from c in db.ACONDICIONAMENTO select c;
            ViewData["acondicionamento"] = new SelectList(acondicionamento, "ID_ACONDICIONAMENTO", "NOME_ACONDICIONAMENTO");
            if (ordem_acabamento == null)
            {
                return HttpNotFound();
            }
            return View(ordem_acabamento);
        }

        [HttpPost]
        [Filtro(Roles = "PCP")]
        public JsonResult Emitir(int id)
        {
            ORDEM_ACABAMENTO ordem_acabamento = db.ORDEM_ACABAMENTO.Find(id);
            if (ordem_acabamento == null)
            {
                return Json(false);
            }

            ordem_acabamento.SITUACAO = eTipoSituacao.Emitido;
            db.Entry(ordem_acabamento).State = EntityState.Modified;
            db.SaveChanges();
            return Json(true);
        }

        [HttpPost]
        [Filtro(Roles = "PCP")]
        public JsonResult Recebimento(int id)
        {
            ORDEM_ACABAMENTO ordem_acabamento = db.ORDEM_ACABAMENTO.Find(id);
            if (ordem_acabamento == null)
            {
                return Json(false);
            }

            ordem_acabamento.SITUACAO = eTipoSituacao.Recebido;
            db.Entry(ordem_acabamento).State = EntityState.Modified;
            db.SaveChanges();
            return Json(true);
        }


        //
        // GET: /OrdemAcabamento/

        [Filtro(Roles = "PCP")]
        public ActionResult Index()
        {
            return View(db.ORDEM_ACABAMENTO.ToList());
        }

        //
        // GET: /OrdemAcabamento/Details/5

        [Filtro(Roles = "PCP")]
        public ActionResult Details(int id = 0)
        {
            ORDEM_ACABAMENTO ordem_acabamento = db.ORDEM_ACABAMENTO.Find(id);
            if (ordem_acabamento == null)
            {
                return HttpNotFound();
            }
            return View(ordem_acabamento);
        }

        //
        // GET: /OrdemAcabamento/Create

        [Filtro(Roles = "PCP")]
        public ActionResult Create()
        {
            ViewBag.ID_PRODUTO = new SelectList(db.PRODUTO, "ID_PRODUTO", "NOME_PRODUTO");
            ViewBag.ID_COR     = new SelectList(db.COR, "ID_COR", "NOME_COR");
            return View();
        }

        //
        // POST: /OrdemAcabamento/Create

        [HttpPost]
        [Filtro(Roles = "PCP")]
        public ActionResult Create(ORDEM_ACABAMENTO ordem_acabamento)
        {
            if (ModelState.IsValid)
            {
                db.ORDEM_ACABAMENTO.Add(ordem_acabamento);
                db.SaveChanges();
                return RedirectToAction("Programado");
            }

            ViewBag.ID_PRODUTO = new SelectList(db.PRODUTO, "ID_PRODUTO", "NOME_PRODUTO");
            ViewBag.ID_COR = new SelectList(db.COR, "ID_COR", "NOME_COR");
            return View(ordem_acabamento);
        }

        //
        // GET: /OrdemAcabamento/Edit/5

        [Filtro(Roles = "PCP")]
        public ActionResult Edit(int id = 0)
        {
            ORDEM_ACABAMENTO ordem_acabamento = db.ORDEM_ACABAMENTO.Find(id);
            if (ordem_acabamento == null)
            {
                return HttpNotFound();
            }
            return View(ordem_acabamento);
        }

        //
        // POST: /OrdemAcabamento/Edit/5

        [HttpPost]
        [Filtro(Roles = "PCP")]
        public ActionResult Edit(ORDEM_ACABAMENTO ordem_acabamento)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ordem_acabamento).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ordem_acabamento);
        }

        //
        // GET: /OrdemAcabamento/Delete/5

        [Filtro(Roles = "PCP")]
        public ActionResult Delete(int id = 0)
        {
            ORDEM_ACABAMENTO ordem_acabamento = db.ORDEM_ACABAMENTO.Find(id);
            if (ordem_acabamento == null)
            {
                return HttpNotFound();
            }
            return View(ordem_acabamento);
        }

        //
        // POST: /OrdemAcabamento/Delete/5

        [Filtro(Roles = "PCP")]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            ORDEM_ACABAMENTO ordem_acabamento = db.ORDEM_ACABAMENTO.Find(id);
            db.ORDEM_ACABAMENTO.Remove(ordem_acabamento);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MalhariaWeb/Views/OrdemAcabamento/Create.cshtml
@model MalhariaWeb.Models.ORDEM_ACABAMENTO

@{
    ViewBag.Title = "Gerar Ordem";
    Layout = "~/Views/_LayoutMalhariaWeb.cshtml";
}

<div class="row">
    <div class="col-md-12">

        <ul class="breadcrumb">
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li class="active">Cadastro</li>
            <li>Ordem de Acabamento</li>
        </ul>

        <div class="panel panel-primary">
            <div class="panel-heading">Ordem de Acabamento</div>
            <div class="panel-body">

                @using (Html.BeginForm("Create", "OrdemAcabamento", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horinzontal", role = "role" }))
                @using (Html.BeginForm())
                {
                    @Html.ValidationSummary(true)
                    <div class="col-md-12">
                        <div class="col-md-2">
                            <div class="form-group">
                                @Html.LabelFor(model => model.ID_PRODUTO, new { @class = "col-md-2 control-label" })
                                @Html.DropDownList("ID_PRODUTO", String.Empty)
                                @Html.ValidationMessageFor(model => model.ID_PRODUTO)
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                @Html.LabelFor(model => model.ID_COR, new { @class = "col-md-2 control-label" })
                                @Html.DropDownList("ID_COR", String.Empty)
                                @Html.ValidationMessageFor(model => model.ID_COR)
                            </div>
                        </div>
                    </div>
    
                    <div class="col-md-12">
                        <div class="col-md-2">
                            <div class="form-group">
                                @Html.LabelFor(model => model.METROS_PROGRAMADOS, new { @class = "col-md-2 control-label" })
                                @Html.TextBoxFor(model => model.METROS_PROGRAMADOS, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.METROS_PROGRAMADOS)
                            </div>

                        </div>

                        <div class="col-md-2">
                            <div class="form-group">
                                @Html.LabelFor(model => model.KILOS_PROGRAMADOS, new { @class = "col-md-2 control-label" })
                                @Html.TextBoxFor(model => model.KILOS_PROGRAMADOS, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.KILOS_PROGRAMADOS)
                            </div>
                        </div>
                    </div>

                    <div class="col-md-12">
                        <div class="col-md-2">
                            <div class="form-group">
                                @Html.LabelFor(model => model.OBSERVACAO, new { @class = "col-md-2 control-label" })
                                @Html.TextAreaFor(model => model.OBSERVACAO)
                                @Html.ValidationMessageFor(model => model.OBSERVACAO)
                            </div>
                        </div>
                    </div>
                    <br>
    
                    <p>
                        <button class="btn btn-success" type="submit" value="Salvar">Gerar Ordem</button>
                    </p>
                }
            </div>
        </div>

    </div>
</div>

<script>


</script>

MalhariaWeb/Views/OrdemAcabamento/Emissao.cshtml
@model MalhariaWeb.Models.ORDEM_ACABAMENTO

@{
    ViewBag.Title = "Emissao";
    Layout = "~/Views/_LayoutMalhariaWeb.cshtml";
}
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary">
            <div class="panel-heading">Emissão Ordem de Acabamento</div>
            <div class="panel-body">

                @using (Html.BeginForm("Emissao", "OrdemAcabamento", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                {
                    @Html.ValidationSummary(true)

                    <div class="form-group">
                        @Html.LabelFor(model => model.ID_ORDEM_ACABAMENTO, new { @class = "col-md-2 control-label" })
                        <div>
                            @Html.DisplayFor(model => model.ID_ORDEM_ACABAMENTO)
                        </div>
                        @Html.LabelFor(model => model.PRODUTO.NOME_PRODUTO, new { @class = "label label-primary" })
                        <div>
                            @Html.DisplayFor(model => model.PRODUTO.NOME_PRODUTO)
                        </div>
                        @Html.LabelFor(model => model.COR.NOME_COR, new { @class = "label label-primary" })
                        <div>
                            @Html.DisplayFor(model => model.COR.NOME_COR)
                        </div>
                        @Html.ValidationMessageFor(model => model.ID_COR)

                    </div>


                    <div class="form-group">
                        @Html.LabelFor(model => model.METROS_PROGRAMADOS, new { @class = "label label-info" })
                        @Html.DisplayFor(model => model.METROS_PROGRAMADOS)
                        @Html.ValidationMessageFor(model => model.METROS_PROGRAMADOS)
                        @Html.LabelFor(model => model.KILOS_PROGRAMADOS, new { @class = "label label-info" })
                        @Html.DisplayFor(model => model.KILOS_PROGRAMADOS)
                        @Html.ValidationMessageFor(model => model.KILOS_PROGRAMADOS)

                        @Html.LabelFor(model => model.METROS_ORIGINAIS, new { @class = "label label-info" })
                        @Html.DisplayFor(model => model.METROS_ORIGINAIS)
                        @Html.ValidationMessageFor(model => model.METROS_ORIGINAIS)
                        @Html.LabelFor(model => model.KILOS_ORIGINAIS, new { @class = "label label-info" })
                        @Html.DisplayFor(model => model.KILOS_ORIGINAIS)
                        @Html.ValidationMessageFor(model => model.KILOS_ORIGINAIS)
                    </div>

                    <div class="col-md-12">
                        @Html.LabelFor(model => model.OBSERVACAO)
                        @Html.DisplayFor(model => model.OBSERVACAO)
                        @Html.ValidationMessageFor(model => model.OBSERVACAO)
                    </div>


                    WebGrid grid = new WebGrid(ajaxUpdateContainerId: "gridContent");
                    grid.Bind(source: Model.ORDEM_ACABAMENTO_PECAS, columnNames: new string[] { "ID_PECA" });

                    <div class="col-md-12">
                        <div id="gridContent">

                            @grid.GetHtml(
    htmlAttributes: new { @class = "table table-bordered table-condensed table-hover" },
    columns: grid.Columns(
    grid.Column("", format: @<text>@Html.CheckBox("ID_ORDEM_ACABAMENTO_PECAS", false, new { @value = @item.ID_ORDEM_ACABAMENTO_PECAS })</text>),
grid.Column("ID_PECA", "#Peça"),
grid.Column("PESO", "Peso"),
grid.Column("METROS", "Metros")
)
)
                        </div>
                    </div>
                }
            </div>
            <div class="panel-footer">
                <a id="modal-incluir-pecas-oa" href="#modal-container-incluir-pecas-oa" role="button" class="btn btn-success" data-toggle="modal" onclick="getPecas()"><i class="icon-plus icon-white"></i>Incluir Peças</a>
                <a class="btn btn-danger" onclick="DeletaPeca()"><i class="icon-trash icon-large icon-white"></i>Excluir Peças</a>
                <input type="button" class="btn btn-success" onclick="EmitirOrdem()" value="Emitir Ordem">
            </div>

            <div id="modal-container-incluir-pecas-oa" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h4 id="myModalIncluir">Escolher peças</h4>
                        </div>
                        @using (Html.BeginForm("InserirPecas", "OrdemAcabamentoPecas"))
                        {
                            <div class="modal-body">
                                @Html.HiddenFor(model => model.ID_ORDEM_ACABAMENTO)
                                <div id="TabelaPeca">
                                </div>

                            </div>
                            <div class="modal-footer">
                                <button class="btn btn-success" type="submit" id="confirmTrue">Adicionar</button>
                            </div>
                        }
                    </div>
                </div>
            </div>
            <div id="modal-container-excluir-pecas-oa" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h3 id="myModalExcluir">Exclusão</h3>
                        </div>
                        <div class="modal-body">
                            <div class="col-md-2" style="float: left">
                                <img alt="48x48" src="~/img/excluir_sels.png" />
                            </div>
                            <div>
                                <p>Deseja excluir todos os itens selecionados?</p>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button class="btn btn-danger" id="confirmFalse" data-dismiss="modal" aria-hidden="true">Não</button>
                            <button class="btn btn-success" id="confirmTrue" onclick="DeletaPeca()">Sim</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        function getPecas() {
            var modelo = {}
            modelo.produto = $("#ID_PRODUTO").val();
            $.getJSON("/Pecas/GetPecasCruas", modelo, function (data) {
                $("#Teste9").remove();
                $("#TabelaPeca").append("<table class='table table-bordered' id='Teste9'></table>");
                $("#Teste9").append("<tr><th></th><th>#Peça</th><th>Peso Liquido</th><th>Metros</th><th>Maquina</th></tr>");
                $.each(data, function (index, d) {
                    $("#Teste9").append("<tr><td><input id='checkboxPecas' type='checkbox' value='" + d.ID_PECA + "' name='checkboxPecas'/></td><td>" + d.ID_PECA + "</td><td>" + d.PESO_LIQUIDO + "</td><td>" + d.METROS + "</td><td>" + d.MAQUINAS.NOME_MAQUINA + "</td></tr>");
                })
            });
        };
        function DeletaPeca() {
            var linha = 0;
            if (confirm("Tem certeza que gostaria de deletar as peças selecionadas?")) {
                $('#gridContent table tr').each(function () {
                    if ($(this).find("input[id='ID_ORDEM_ACABAMENTO_PECAS']").length > 0) {
                        if ($(this).find("input[id='ID_ORDEM_ACABAMENTO_PECAS']")[0].checked == true) {
                            var data = { ID: ID_ORDEM_ACABAMENTO_PECAS[linha] };
                            var temp = $(this);
                            $.post("/OrdemAcabamentoPecas/DeletaPeca", { id: data.ID.value }, function (response) {
                                if (response == true) {
                                    temp.remove();
                                }
                            });
                        }
                        linha++;
                    }
                });

            }
        };
        function EmitirOrdem() {
            if (confirm("Tem certeza que gostaria de emitir essa ordem?")) {
                var ordem = $('#ID_ORDEM_ACABAMENTO').val();
                $.post("/OrdemAcabamento/Emitir", { id: ordem }, function (response) {
                    if (response == true) {
                        document.location = '/OrdemAcabamento/Programado';
                    }
                })
            }
        }
    </script>

MalhariaWeb/Views/OrdemAcabamento/Producao.cshtml
@model IEnumerable<MalhariaWeb.Models.ORDEM_ACABAMENTO>
@{
    ViewBag.Title = "Producao";
    Layout = "~/Views/_LayoutMalhariaWeb.cshtml";
}

<div class="row">
    <div class="col-md-12">

        <ul class="breadcrumb">
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li class="active">Cadastro</li>
            <li>@Html.ActionLink("Ordem de Acabamento", "Index", "OrdemAcabamento")</li>
            <li class="active">Lista de Ordens Acabamentos Programadas</li>
        </ul>

        <div>
            <a class="btn btn-success" onclick="ConfirmarRecebimento()"><i class="icon-plus icon-white"></i>Recebimento</a>
            <a class="btn btn-danger"><i class="icon-trash icon-large icon-white"></i>Cancelar Emissão</a>
        </div>
        <table class="table table-bordered" id="gridContent">
            <tr>
                <th></th>
                <th>
                    @Html.DisplayNameFor(model => model.ID_ORDEM_ACABAMENTO)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PRODUTO.NOME_PRODUTO)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.COR.NOME_COR)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.METROS_PROGRAMADOS)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.KILOS_PROGRAMADOS)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.METROS_ORIGINAIS)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.KILOS_ORIGINAIS)
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.CheckBox("ID_ORDEM_ACABAMENTO", false, new { @value = item.ID_ORDEM_ACABAMENTO })
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ID_ORDEM_ACABAMENTO)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PRODUTO.NOME_PRODUTO)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.COR.NOME_COR)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.METROS_PROGRAMADOS)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.KILOS_PROGRAMADOS)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.METROS_ORIGINAIS)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.KILOS_ORIGINAIS)
                    </td>
                </tr>
            }

        </table>
    </div>
</div>

<script type="text/javascript">
    function ConfirmarRecebimento() {
        var linha = 0;
        if (confirm("Confirma recebimentos das ordens selecionadas?")) {
            $('#gridContent tr').each(function () {
                if ($(this).find("input[id='ID_ORDEM_ACABAMENTO']").length > 0) {
                    if ($(this).find("input[id='ID_ORDEM_ACABAMENTO']")[0].checked == true) {
                        var data = { ID: ID_ORDEM_ACABAMENTO[linha] };
                        var temp = $(this);
                        $.post("/OrdemAcabamento/Recebimento", { id: data.ID.value }, function (response) {
                            if (response == true) {
                                temp.remove();
                            }
                        });
                    }
                    linha++;
                }
            });

        }
    }
</script>

MalhariaWeb/Views/OrdemAcabamento/Programado.cshtml
@model IEnumerable<MalhariaWeb.Models.ORDEM_ACABAMENTO>

@{
    ViewBag.Title = "Programado";
    Layout = "~/Views/_LayoutMalhariaWeb.cshtml";
}

<div class="row">
    <div class="col-md-12">

        <ul class="breadcrumb">
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li class="active">Cadastro</li>
            <li>@Html.ActionLink("Ordem de Acabamento", "Index", "OrdemAcabamento")</li>
            <li class="active">Lista de Ordens Acabamentos Programadas</li>
        </ul>


        <table class="table table-bordered">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ID_ORDEM_ACABAMENTO)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PRODUTO.NOME_PRODUTO)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.COR.NOME_COR)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.METROS_PROGRAMADOS)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.KILOS_PROGRAMADOS)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.METROS_ORIGINAIS)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.KILOS_ORIGINAIS)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ID_ORDEM_ACABAMENTO)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PRODUTO.NOME_PRODUTO)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.COR.NOME_COR)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.METROS_PROGRAMADOS)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.KILOS_PROGRAMADOS)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.METROS_ORIGINAIS)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.KILOS_ORIGINAIS)
                    </td>
                    <td>
                        @Html.ActionLink("Emissão", "Emissao", new { id = item.ID_ORDEM_ACABAMENTO })
                    </td>
                </tr>
            }

        </table>
    </div>
</div>