MalhariaWeb/Models/PECAS.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;

namespace MalhariaWeb.Models
{
    public class PECAS
    {
        [Key]
        [DisplayName("Id")]
        public int ID_PECA { get; set; }
        [DisplayName("Produto")]
        public int ID_PRODUTO { get; set; }
        [DisplayName("Unidade Medida")]
        public int ID_UNIDADE_MEDIDA { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        [DisplayName("Metros")]
        public Nullable<double> METROS { get; set; }
        [DisplayName("Deposito")]
        public int ID_DEPOSITO { get; set; }
        [DisplayName("Ordem Acabamento")]
        public Nullable<int> ID_ORDEM_ACABAMENTO { get; set; }
        [DisplayName("Operador")]
        public Nullable<int> ID_OPERADOR { get; set; }
        [DisplayName("Data Entrada")]
        public Nullable<System.DateTime> DATA_ENTRADA { get; set; }
        [DisplayName("Hora Entrada")]
        public Nullable<System.DateTime> HORA_ENTRADA { get; set; }
        [DisplayName("Situação")]
        public eSituacaoPeca SITUACAO { get; set; }
        [DisplayName("Peso Liquido")]
        [DisplayFormat(DataFormatString = "{0:#,##0.000#}", ApplyFormatInEditMode = true)]
        public double PESO_LIQUIDO { get; set; }
        [DisplayName("Cor")]
        public Nullable<int> ID_COR { get; set; }
        [DisplayName("Qualidade")]
        public eQualidadePeca QUALIDADE { get; set; }
        [DisplayName("Acondicionamento")]
        public int ID_ACONDICIONAMENTO { get; set; }
        [DisplayName("Data Saida")]
        public Nullable<System.DateTime> DATA_SAIDA { get; set; }
        [DisplayName("Maquina")]
        public Nullable<int> ID_MAQUINA { get; set; }
        [DisplayName("Largura")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public double LARGURA { get; set; }
        [DisplayName("Peça Dividida")]
        public Nullable<bool> EH_PECA_DIVIDIDA { get; set; }
        [DisplayName("Gramatura")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public Nullable<double> GRAMATURA { get; set; }
        [DisplayName("Peso Bruto")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public double PESO_BRUTO { get; set; }
        [DisplayName("Tipo Peça")]
        public eTipoPeca TIPO_PECA { get; set; }
        [DisplayName("Peça Origem")]
        public Nullable<int> PECA_ORIGEM { get; set; }

        public virtual PRODUTO PRODUTO { get; set; }
        public virtual UNIDADE_MEDIDA UNIDADE_MEDIDA { get; set; }
        public virtual DEPOSITO DEPOSITO { get; set; }
        public virtual OPERADOR OPERADOR { get; set; }
        public virtual COR COR { get; set; }
        public virtual ACONDICIONAMENTO ACONDICIONAMENTO { get; set; }
        public virtual MAQUINAS MAQUINAS { get; set; }

    }

    public enum eSituacaoPeca
    {
        Disponivel = 0,
        Baixado = 1,
        Producao = 2,
        PecaMae = 3,
        Revisado = 4,
        Pesagem = 5
    }

    public enum eTipoPeca
    {
        Fios = 0,
        Cru = 1,
        Acabado = 2
    }

    public enum eQualidadePeca
    {
        Primeira = 0,
        Segunda = 1,
        Terceira = 2
    }

}

MalhariaWeb/Controllers/PecasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MalhariaWeb.Models;
using MalhariaWeb.Roles;

namespace MalhariaWeb.Controllers
{
    public class PecasController : Controller
    {
        private ContextDB db = new ContextDB();

        //
        // GET: /Pecas/

        [Filtro(Roles = "Operador")]
        public ActionResult Index()
        {
            var pecas = db.PECAS.Include(p => p.PRODUTO).Include(p => p.UNIDADE_MEDIDA).Include(p => p.DEPOSITO).Include(p => p.OPERADOR).Include(p => p.COR).Include(p => p.ACONDICIONAMENTO).Include(p => p.MAQUINAS);
            return View(pecas.ToList());
        }

        //
        // GET: /Pecas/Details/5

        [Filtro(Roles = "Operador")]
        public ActionResult Details(int id = 0)
        {
            PECAS pecas = db.PECAS.Find(id);
            if (pecas == null)
            {
                return HttpNotFound();
            }
            return View(pecas);
        }

        // Get: /Pecas/CreatePecaCrua
        [Filtro(Roles = "Operador")]
        public ActionResult CreatePecaCrua()
        {
            ViewBag.ID_ACONDICIONAMENTO = new SelectList(db.ACONDICIONAMENTO, "ID_ACONDICIONAMENTO", "NOME_ACONDICIONAMENTO");
            ViewBag.ID_DEPOSITO         = new SelectList(db.DEPOSITO, "ID_DEPOSITO", "NOME_DEPOSITO");
            ViewBag.ID_MAQUINA          = new SelectList(db.MAQUINAS, "ID_MAQUINA", "NOME_MAQUINA");
            ViewBag.ID_OPERADOR         = new SelectList(db.OPERADOR, "ID_OPERADOR", "NOME_OPERADOR");
            ViewBag.ID_PRODUTO          = new SelectList(db.PRODUTO, "ID_PRODUTO", "NOME_PRODUTO");
            ViewBag.ID_UNIDADE_MEDIDA   = new SelectList(db.UNIDADE_MEDIDA, "ID_UNIDADE_MEDIDA", "NOME_UNIDADE_MEDIDA");
            return View();
        }


        [Filtro(Roles = "Operador")]
        public ActionResult DetalhesPecasCruas(int id = 0)
        {
            PECAS pecas = db.PECAS.Find(id);
            if (pecas == null) 
            {
                return HttpNotFound();
            }
            return View(pecas);
        }

        [HttpPost]
        [Filtro(Roles = "Operador")]
        public ActionResult InserirPecaAcabada(FormCollection form)
        {
            int idordem   = Convert.ToInt32(form.GetValue("ID_ORDEM_ACABAMENTO").AttemptedValue);
            int idcor     = Convert.ToInt32(form.GetValue("ID_COR").AttemptedValue);
            int idproduto = Convert.ToInt32(form.GetValue("ID_PRODUTO").AttemptedValue);
            eQualidadePeca  vqualidade = (eQualidadePeca)Convert.ToInt32(form.GetValue("Qualidade").AttemptedValue);
            double metros;
            if (form.GetValue("Metros").AttemptedValue == String.Empty)
                metros = 0.00;
            else
                metros = Convert.ToDouble(form.GetValue("Metros").AttemptedValue);
            double largura;
            if (form.GetValue("Largura").AttemptedValue == String.Empty)
                largura = 0.00;
            else 
                largura = Convert.ToDouble(form.GetValue("Largura").AttemptedValue);
            int acondicionamento = Convert.ToInt32(form.GetValue("Acondicionamento").AttemptedValue);
            int vpecacrua = Convert.ToInt32(form.GetValue("pecacrua").AttemptedValue);

            PECAS pecacrua = db.PECAS.Find(vpecacrua);
            pecacrua.SITUACAO = eSituacaoPeca.Revisado;
            db.Entry(pecacrua).State = EntityState.Modified;

            PECAS pecaacabada = new PECAS();
            pecaacabada.UNIDADE_MEDIDA = pecacrua.UNIDADE_MEDIDA;
            pecaacabada.DATA_ENTRADA = DateTime.Now.Date;
            pecaacabada.HORA_ENTRADA = DateTime.Now;
            pecaacabada.TIPO_PECA = eTipoPeca.Acabado;
            pecaacabada.METROS = metros;
            pecaacabada.LARGURA = largura;
            pecaacabada.ID_COR = idcor;
            pecaacabada.ID_PRODUTO = idproduto;
            pecaacabada.ID_ACONDICIONAMENTO = acondicionamento;
            pecaacabada.ID_DEPOSITO = 3;
            db.PECAS.Add(pecaacabada);
            db.SaveChanges();

            return RedirectToAction("Revisao", "OrdemAcabamento", new { id = idordem });
        }

        //
        // POST: /Pecas/CreateCrua
        [HttpPost]
        [Filtro(Roles = "Operador")]
        public ActionResult CreatePecaCrua(PECAS pecas)
        {
            if (ModelState.IsValid)
            {
                pecas.DATA_ENTRADA = DateTime.Now.Date;
                pecas.HORA_ENTRADA = DateTime.Now;
                pecas.TIPO_PECA = eTipoPeca.Cru;
                pecas.EH_PECA_DIVIDIDA = false;
                pecas.SITUACAO = eSituacaoPeca.Disponivel;
                pecas.PESO_LIQUIDO = pecas.PESO_BRUTO - db.ACONDICIONAMENTO.Find(pecas.ID_ACONDICIONAMENTO).VALOR;
                db.PECAS.Add(pecas);
                db.SaveChanges();
                return RedirectToAction("CreatePecaCrua");
            }

            ViewBag.ID_ACONDICIONAMENTO = new SelectList(db.ACONDICIONAMENTO, "ID_ACONDICIONAMENTO", "NOME_ACONDICIONAMENTO", pecas.ID_ACONDICIONAMENTO);
            ViewBag.ID_DEPOSITO = new SelectList(db.DEPOSITO, "ID_DEPOSITO", "NOME_DEPOSITO", pecas.ID_DEPOSITO);
            ViewBag.ID_MAQUINA = new SelectList(db.MAQUINAS, "ID_MAQUINA", "NOME_MAQUINA", pecas.ID_MAQUINA);
            ViewBag.ID_OPERADOR = new SelectList(db.OPERADOR, "ID_OPERADOR", "NOME_OPERADOR", pecas.ID_OPERADOR);
            ViewBag.ID_PRODUTO = new SelectList(db.PRODUTO, "ID_PRODUTO", "NOME_PRODUTO", pecas.ID_PRODUTO);
            ViewBag.ID_UNIDADE_MEDIDA = new SelectList(db.UNIDADE_MEDIDA, "ID_UNIDADE_MEDIDA", "NOME_UNIDADE_MEDIDA", pecas.ID_UNIDADE_MEDIDA);
            return View(pecas);
        }

        //
        // GET: /Pecas/Create

        [Filtro(Roles = "Operador")]
        public ActionResult Create()
        {
            ViewBag.ID_ACONDICIONAMENTO = new SelectList(db.ACONDICIONAMENTO, "ID_ACONDICIONAMENTO", "NOME_ACONDICIONAMENTO");
            ViewBag.ID_COR = new SelectList(db.COR, "ID_COR", "NOME_COR");
            ViewBag.ID_DEPOSITO = new SelectList(db.DEPOSITO, "ID_DEPOSITO", "NOME_DEPOSITO");
            ViewBag.ID_MAQUINA = new SelectList(db.MAQUINAS, "ID_MAQUINA", "NOME_MAQUINA");
            ViewBag.ID_OPERADOR = new SelectList(db.OPERADOR, "ID_OPERADOR", "NOME_OPERADOR");
            ViewBag.ID_PRODUTO = new SelectList(db.PRODUTO, "ID_PRODUTO", "NOME_PRODUTO");
            ViewBag.ID_UNIDADE_MEDIDA = new SelectList(db.UNIDADE_MEDIDA, "ID_UNIDADE_MEDIDA", "NOME_UNIDADE_MEDIDA");
            return View();
        }

        //
        // POST: /Pecas/Create

        [HttpPost]
        [Filtro(Roles = "Operador")]
        public ActionResult Create(PECAS pecas)
        {
            if (ModelState.IsValid)
            {
                db.PECAS.Add(pecas);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_ACONDICIONAMENTO = new SelectList(db.ACONDICIONAMENTO, "ID_ACONDICIONAMENTO", "NOME_ACONDICIONAMENTO", pecas.ID_ACONDICIONAMENTO);
            ViewBag.ID_COR = new SelectList(db.COR, "ID_COR", "NOME_COR", pecas.ID_COR);
            ViewBag.ID_DEPOSITO = new SelectList(db.DEPOSITO, "ID_DEPOSITO", "NOME_DEPOSITO", pecas.ID_DEPOSITO);
            ViewBag.ID_MAQUINA = new SelectList(db.MAQUINAS, "ID_MAQUINA", "NOME_MAQUINA", pecas.ID_MAQUINA);
            ViewBag.ID_OPERADOR = new SelectList(db.OPERADOR, "ID_OPERADOR", "NOME_OPERADOR", pecas.ID_OPERADOR);
            ViewBag.ID_PRODUTO = new SelectList(db.PRODUTO, "ID_PRODUTO", "NOME_PRODUTO", pecas.ID_PRODUTO);
            ViewBag.ID_UNIDADE_MEDIDA = new SelectList(db.UNIDADE_MEDIDA, "ID_UNIDADE_MEDIDA", "NOME_UNIDADE_MEDIDA", pecas.ID_UNIDADE_MEDIDA);
            return View(pecas);
        }

        //
        // GET: /Pecas/Edit/5

        [Filtro(Roles = "Operador")]
        public ActionResult Edit(int id = 0)
        {
            PECAS pecas = db.PECAS.Find(id);
            if (pecas == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_ACONDICIONAMENTO = new SelectList(db.ACONDICIONAMENTO, "ID_ACONDICIONAMENTO", "NOME_ACONDICIONAMENTO", pecas.ID_ACONDICIONAMENTO);
            ViewBag.ID_COR = new SelectList(db.COR, "ID_COR", "NOME_COR", pecas.ID_COR);
            ViewBag.ID_DEPOSITO = new SelectList(db.DEPOSITO, "ID_DEPOSITO", "NOME_DEPOSITO", pecas.ID_DEPOSITO);
            ViewBag.ID_MAQUINA = new SelectList(db.MAQUINAS, "ID_MAQUINA", "NOME_MAQUINA", pecas.ID_MAQUINA);
            ViewBag.ID_OPERADOR = new SelectList(db.OPERADOR, "ID_OPERADOR", "NOME_OPERADOR", pecas.ID_OPERADOR);
            ViewBag.ID_PRODUTO = new SelectList(db.PRODUTO, "ID_PRODUTO", "NOME_PRODUTO", pecas.ID_PRODUTO);
            ViewBag.ID_UNIDADE_MEDIDA = new SelectList(db.UNIDADE_MEDIDA, "ID_UNIDADE_MEDIDA", "NOME_UNIDADE_MEDIDA", pecas.ID_UNIDADE_MEDIDA);
            return View(pecas);
        }

        //
        // POST: /Pecas/Edit/5

        [HttpPost]
        [Filtro(Roles = "Operador")]
        public ActionResult Edit(PECAS pecas)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pecas).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_ACONDICIONAMENTO = new SelectList(db.ACONDICIONAMENTO, "ID_ACONDICIONAMENTO", "NOME_ACONDICIONAMENTO", pecas.ID_ACONDICIONAMENTO);
            ViewBag.ID_COR = new SelectList(db.COR, "ID_COR", "NOME_COR", pecas.ID_COR);
            ViewBag.ID_DEPOSITO = new SelectList(db.DEPOSITO, "ID_DEPOSITO", "NOME_DEPOSITO", pecas.ID_DEPOSITO);
            ViewBag.ID_MAQUINA = new SelectList(db.MAQUINAS, "ID_MAQUINA", "NOME_MAQUINA", pecas.ID_MAQUINA);
            ViewBag.ID_OPERADOR = new SelectList(db.OPERADOR, "ID_OPERADOR", "NOME_OPERADOR", pecas.ID_OPERADOR);

MalhariaWeb/Views/Pecas/CreatePecaCrua.cshtml
@model MalhariaWeb.Models.PECAS

@{
    ViewBag.Title = "Gerar Peça Crua";
    Layout = "~/Views/_LayoutMalhariaWeb.cshtml";
}

@using (Html.BeginForm("CreatePecaCrua", "Pecas", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horinzontal", role = "role" }))
{
    @Html.ValidationSummary(true)

    <div class="row">

        <div class="panel panel-primary">
            <div class="panel-heading">Cadastro de Pedidos</div>
            <div class="panel-body">

                <div class="col-md-12">
                    <div class="form-group">
                        @Html.LabelFor(model => model.ID_PRODUTO, new { @class = "col-md-2 control-label" })
                        @Html.DropDownList("ID_PRODUTO", String.Empty)
                        @Html.ValidationMessageFor(model => model.ID_PRODUTO)
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        @Html.LabelFor(model => model.ID_UNIDADE_MEDIDA, new { @class = "col-md-2 control-label" })
                        @Html.DropDownList("ID_UNIDADE_MEDIDA", String.Empty)
                        @Html.ValidationMessageFor(model => model.ID_UNIDADE_MEDIDA)
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        @Html.LabelFor(model => model.ID_DEPOSITO, new { @class = "col-md-2 control-label" })
                        @Html.DropDownList("ID_DEPOSITO", String.Empty)
                        @Html.ValidationMessageFor(model => model.ID_DEPOSITO)
                    </div>
                </div>



                <div class="col-md-2">
                    <div class="form-group">
                        @Html.Label("Tecelão")
                        @Html.DropDownList("ID_OPERADOR", String.Empty)
                        @Html.ValidationMessageFor(model => model.ID_OPERADOR)
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        @Html.LabelFor(model => model.ID_MAQUINA, new { @class = "col-md-2 control-label" })
                        @Html.DropDownList("ID_MAQUINA", String.Empty)
                        @Html.ValidationMessageFor(model => model.ID_MAQUINA)
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        @Html.LabelFor(model => model.QUALIDADE, new { @class = "col-md-2 control-label" })
                        @Html.DropDownListFor(model => model.QUALIDADE, Enum.GetValues(typeof(MalhariaWeb.Models.eQualidadePeca)).Cast<MalhariaWeb.Models.eQualidadePeca>().Select(v => new SelectListItem
               {
                   Text = v.ToString().Replace("_", " "),
                   Value = ((int)v).ToString()
               }), "[Select]")
                        @Html.ValidationMessageFor(model => model.QUALIDADE)
                    </div>
                </div>




                <div class="col-md-2">
                    <div class="form-group">
                        @Html.LabelFor(model => model.LARGURA, new { @class = "col-md-2 control-label" })
                        @Html.TextBoxFor(model => model.LARGURA, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.LARGURA)
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        @Html.LabelFor(model => model.GRAMATURA, new { @class = "col-md-2 control-label" })
                        @Html.TextBoxFor(model => model.GRAMATURA, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.GRAMATURA)
                    </div>
                </div>



                <div class="form-group">
                    @Html.LabelFor(model => model.ID_ACONDICIONAMENTO, new { @class = "col-md-2 control-label" })
                    @Html.DropDownList("ID_ACONDICIONAMENTO", String.Empty)
                    @Html.ValidationMessageFor(model => model.ID_ACONDICIONAMENTO)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.METROS, new { @class = "col-md-2 control-label" })
                    @Html.TextBoxFor(model => model.METROS, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.METROS)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PESO_BRUTO, new { @class = "col-md-2 control-label" })
                    @Html.TextBoxFor(model => model.PESO_BRUTO, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.PESO_BRUTO)
                </div>

            </div>
            <div class="panel-footer">

                <button class="btn btn-success" type="submit" value="Salvar">Gerar Peça</button>
            </div>
        </div>
    </div>
}

MalhariaWeb/Views/Pecas/Details.cshtml
@model MalhariaWeb.Models.PECAS

@{
    Layout = null;
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>PECAS</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ID_PECA)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ID_PECA)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PRODUTO.NOME_PRODUTO)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PRODUTO.NOME_PRODUTO)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UNIDADE_MEDIDA.NOME_UNIDADE_MEDIDA)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UNIDADE_MEDIDA.NOME_UNIDADE_MEDIDA)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.METROS)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.METROS)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DEPOSITO.NOME_DEPOSITO)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DEPOSITO.NOME_DEPOSITO)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ORDEM_ACABAMENTO.OBSERVACAO)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ORDEM_ACABAMENTO.OBSERVACAO)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.OPERADOR.NOME_OPERADOR)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.OPERADOR.NOME_OPERADOR)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DATA_ENTRADA)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DATA_ENTRADA)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.HORA_ENTRADA)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.HORA_ENTRADA)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.SITUACAO)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SITUACAO)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PESO_LIQUIDO)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PESO_LIQUIDO)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.COR.NOME_COR)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.COR.NOME_COR)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.QUALIDADE)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.QUALIDADE)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.TIPO)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TIPO)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ACONDICIONAMENTO.NOME_ACONDICIONAMENTO)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ACONDICIONAMENTO.NOME_ACONDICIONAMENTO)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DATA_SAIDA)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DATA_SAIDA)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.MAQUINAS.NOME_MAQUINA)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.MAQUINAS.NOME_MAQUINA)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LARGURA)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LARGURA)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.EH_PECA_DIVIDIDA)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.EH_PECA_DIVIDIDA)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.GRAMATURA)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.GRAMATURA)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PESO_BRUTO)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PESO_BRUTO)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.TIPO_PECA.NOME_TIPO_PECA)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TIPO_PECA.NOME_TIPO_PECA)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PECA_ORIGEM)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PECA_ORIGEM)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id=Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>